"""TODO: implement module."""
from datetime import date
from collections.abc import Iterable, Sequence
from fantasy_analytics_engine.domain.models import (
    HitterGameStat,
    PitcherGameStat,
    FantasyPointEvent,
    WeeklyFantasyPoints,
    ReplacementLevelPoint,
    PlayerVOR,
)

class Repository:
    # This is the raw data
    def upsert_hitter_game_stats(self, rows: Iterable[HitterGameStat]) -> None: ...
    def upsert_pitcher_game_stats(self, rows: Iterable[PitcheGameStat]) -> None: ...
    def get_hitter_game_stats(self, start_date: date, end_date: date) -> Sequence[HitterGameStat]: ...
    def get_pitcher_game_stats(self, start_date: date, end_date: date) -> Sequence[PitcherGameStat]: ...
    
    # This is the derived data
    def upsert_fantasy_points_events(self, rows: Iterable[FantasyPointEvent]) -> None: ...
    def get_fantasy_point_events(self, start_date: date, end_date: date) -> Sequence[FantasyPointEvent]: ...
    
    def upsert_weekly_fantasy_points(self, rows: Iterable[WeeklyFantasyPoints]) -> None: ...
    def get_weekly_fantasy_points(self, start_date: date, end_date: date) -> Sequence[WeeklyFantasyPoints]: ...
    
    def upsert_replacement_levels(self, rows: Iterable[ReplacementLevelPoint]) -> None: ...
    def get_replacement_levels(self, start_date: date, end_date: date) -> Sequence[ReplacementLevelPoint]: ...
    
    def upsert_player_vor(self, rows: Iterable[PlayerVOR]) -> None: ...
    def get_latest_player_vor(self, as_of: date) -> Sequence[PlayerVOR]: ...